### ISSUE TITLE
preamble

### ISSUE THREAD

**Issue by mlinksva** [copyleft-next/copyleft-next#12]
re removing premable in https://lwn.net/Articles/505702/ Greg Maxwell wrote:

"Thats unfortunate, because the GPL is full of ambiguity once you stray from the direct use cases that were considered during drafting. The preamble sets a framework for interpreting the agreement in terms of end goals and not just mechanisms.

Absent such principled guidance reasonable minds are far more likely to disagree about the probable outcome of litigation and so would be more likely to end up there. A boon for trial attorneys, perhaps, but not for free software."

It is too bad the GNU GPL is a nonfree document, necessitating removal of the preamble. If there's anything to Greg's argument (I'm ignorant; has the GNU GPL preamble played a role in any dispute? Is that the right question?) then GPL.next ought have its own preamble.

**Comment by richardfontana** [comment]
I think there is _something_ to the argument, but I don't think in practice the GNU GPL Preambles have actually served this purpose. We could achieve something similar through a clause in the license proper providing guidance as to how the license is to be construed. 

I'm pretty sure I don't want a Preamble though mainly it's to make the document shorter. Closing this issue, but the desirability of a rule-of-construction sort of provision should be an ongoing consideration.

**Comment by richardfontana** [comment]
A simple 'general rule of construction' section was added in https://github.com/richardfontana/copyleft-next/commit/4dda980f22c139f38681fd311d8cdb88048cd045
