### ISSUE TITLE
You should not be using "GPL" in the name of your license.

### ISSUE THREAD

**Issue by sneak** [copyleft-next/copyleft-next#13]
It's not your term, and it's confusing.

**Comment by richardfontana** [comment]
I have argued that "GPL" is a generic term ("general public license"); for an early non-GNU example of its generic use see http://opensource.org/licenses/nethack.php. Nevertheless I'm open to a different name, such as "copyleft.next" (as one potential participant has suggested).

**Comment by richardfontana** [comment]
In accordance with governance rules for the project, the name has been changed to Copyleft.next, reflecting the preferences of a majority of the project's committers.

**Comment by richardfontana** [comment]
@GHANONTEST sorry, I failed to notice the beginning of your comment. There are basically two licenses covering the GNU GPL text. One is the formal one you've quoted above. The other, not quite as restrictive, is stated informally in the GNU licenses FAQ: http://www.gnu.org/licenses/gpl-faq.html#ModifyGPL. This is not a free license in the free cultural works sense, but it is sufficiently liberal to allow the creation of derivative license texts without much difficulty.

**Comment by richardfontana** [comment]
@GHANONTEST the current text is GNU GPL/AGPL compatible through an explicit relicensability clause. This makes it one-way compatible with all existing GNU GPL-licensed software.

**Comment by sneak** [comment]
The name is changed, this bug is fixed. Please close #13 and take your metadiscussion to another, as I keep getting these notification emails unrelated to the name bug I filed. 

-jp

## 

Jeffrey Paul  +1-312-361-0355
5539 AD00 DE4C 42F3 AFE1 1575 0524 43F4 DF2A 55C2

**Comment by richardfontana** [comment]
@GHANONTEST I will respect @sneak's wishes and not respond further here (apart from this comment). @sneak, my apologies.
