### ISSUE TITLE
GPL.copyfarleft? 

### ISSUE THREAD

**Issue by bakagirl** [copyleft-next/copyleft-next#14]
Upon seeing this project, I couldn't help but wonder if this might be a neat way to make a version of the GPL which could be on the offensive side of freedom rather than the defensive stance the GPL has?

Apologies if this line of thought is out of the scope of what this project hopes to achieve. If anyone is interested in this idea at all, i'd recommend these two posts:

http://p2pfoundation.net/Peer_Production_License 
http://p2pfoundation.net/Copyfarleft

Cheers for any input and best of luck with the project.

**Comment by richardfontana** [comment]
Very interesting; I was not too familiar with such efforts. However, a design goal of this project is to implement strong copyleft as traditionally understood.
