### ISSUE TITLE
Choice of law provision?

### ISSUE THREAD

**Issue by richardfontana** [copyleft-next/copyleft-next#21]
@pchestek notes the absence of a choice of law provision. I am opening this as an issue here. The absence is intentional (it follows the absence in all versions of the GPL license family) but it is worth considering whether an approach like that taken in, say, MPL 2.0 might be appropriate. Worth noting that the orthodox FSF view is that choice of law clauses are GPL-incompatible, but the rationale for this view (other than the "Anti-Freedonia" hypothetical) is unclear.

**Comment by westonkdavis** [comment]
The MPL 2.0

> Any litigation relating to this License may be brought only in the courts of a jurisdiction where the defendant maintains its principal place of business and such litigation shall be governed by laws of that jurisdiction, without reference to its conflict-of-law provisions. Nothing in this Section shall prevent a party’s ability to bring cross-claims or counter-claims.
1. Only contemplates business use?
2. Is another way to identify/claim a source?
3. Combines choice of law and choice of venue.

**Comment by richardfontana** [comment]
Hmm... reading it now, I don't think the MPL 2.0 approach will work for copyleft-next. Curious to read up on the rationale though.

**Comment by westonkdavis** [comment]
Mozilla Public License 2.0: Redline from MPL 1.1 @ http://www.mozilla.org/MPL/2.0/differences.html

What is...

```
Mozilla Public License 2.0
```

> "8. Litigation
> 
> Any litigation relating to this License may be brought only in the courts of a jurisdiction where the defendant maintains its principal place of business and such litigation shall be governed by laws of that jurisdiction, without reference to its conflict-of-law provisions. Nothing in this Section shall prevent a party’s ability to bring cross-claims or counter-claims."

...once was...

```
Mozilla Public License 1.1
```

> "11. Miscellaneous
> 
> This License represents the complete agreement concerning subject matter hereof. If any provision of this License is held to be unenforceable, such provision shall be reformed only to the extent necessary to make it enforceable. **This License shall be governed by California law provisions (except to the extent applicable law, if any, provides otherwise), excluding its conflict-of-law provisions. With respect to disputes in which at least one party is a citizen of, or an entity chartered or registered to do business in the United States of America, any litigation relating to this License shall be subject to the jurisdiction of the Federal Courts of the Northern District of California, with venue lying in Santa Clara County, California, with the losing party responsible for costs, including without limitation, court costs and reasonable attorneys' fees and expenses.** The application of the United Nations Convention on Contracts for the International Sale of Goods is expressly excluded. Any law or regulation which provides that the language of a contract shall be construed against the drafter shall not apply to this License."

**Comment by pchestek** [comment]
To clarify, I was thinking only of choice of law, not jurisdiction or
venue.  So you could pick a body of law that would apply to have some more
assurance of predictable interpretation (assuming a local court would
respect the choice, which it may not), but you don't have to address
jurisdiction (and I think trying to force jurisdiction would be very
unfriendly).

Pam

**Comment by westonkdavis** [comment]
I start to see a link between Choice of Law and Moral Rights/Attribution rights, which could provide troublesome, as noted in Issue https://github.com/richardfontana/copyleft-next/issues/22, if your flavor of law completely follows the Berne Convention, I think you run into problem with the ability to access and distribute the code.

I agree with you on the jurisdiction as well Pam.

**Comment by westonkdavis** [comment]
> "We want to say that they are either in cyberspace or in real space. We have this desire because we want to know **which space is responsible**. Which space has **jurisdiction** over them? Which space rules?
> 
> The answer is both. Whenever anyone is _in_ cyberspace, she is also here, in real space. Whenever one is subject to the norms of a cyberspace community, one is also living within a community in real space. You are always in both places if you are there, and the norms of both places apply. The problem for law is to work out how the norms of the two communities are to apply given that the subject to whom they apply may be in both places at once."

 **Lawrence Lessig,** _Code and Other Laws of Cyberspace_, p. 190

**Comment by pchestek** [comment]
I've thought about it and my current opinion is that the license doesn't need a choice of law provision. There are more  interpretations of open source licenses by foreign courts than US and they seem to be doing fine with it. So it may cause more trouble to ask a court to apply law it is unfamiliar with, particularly US law which is very convoluted. It would be better to have review by foreign lawyers to assure that the license will be appropriately interpreted in various jurisdictions rather than try to impose a single body of law.

**Comment by westonkdavis** [comment]
Maybe just a conflict of laws provision with regard to choice of laws with possible negative implications?

(Also assuming the clause would up)

Although I always get weary the more things that are specifically included/excluded/called out

**Comment by richardfontana** [comment]
Okay. No choice of law. Closing this issue!

**Comment by erkinalp** [comment]
"Where incident happened"
