### ISSUE TITLE
Should sec. 4 indicate that child-of-automatic-licensing is a 'condition' on Distribution?

### ISSUE THREAD

**Issue by richardfontana** [copyleft-next/copyleft-next#28]
@pchestek fork removes reference to the pass-through/child-of-automatic-licensing section as one of the 'conditions' of the license, including in section 4.

Assume it may not be preposterous to characterize this as a kind of condition, what are the consequences of omitting reference to it in section 4? I was aware of this issue previously but assumed that there was no harm in sweeping it in as though it were a condition. 

I suppose my view has been that it can be seen as an implied condition on the mere redistributor.

**Comment by pchestek** [comment]
Condition in what way? As worded, it is merely clarification of how the rights flow. The parties affected by this paragraph are the grantor and the distributee only; the licensee-distributor has no role. There is no positive action, or abstention from an act, required from the licensee-distributor, so there's nothing they could do that would be a failure to meet a condition.

**Comment by richardfontana** [comment]
Closed by accident. Issue 28 is not a duplicate of 27; I was confusing sections 3 and 4.

**Comment by richardfontana** [comment]
Actually, this one was taken care of in 48dab4ceb4a382be9448799fedd2b5076f0f6bd7. Closing.
