### ISSUE TITLE
URLs and the developing world

### ISSUE THREAD

**Issue by 11Kilobytes** [copyleft-next/copyleft-next#37]
I'm not sure if not requiring people to give source code on tangible mediums such as CDs, USBs and so on, if they give out object code embodied in a product, or on such tangible mediums, is just. People in the developing world, generally speaking, don't have the bandwidth to download 300MBs of source code from the internet. I suppose that in the future, this situation might improve but as a South African I'm not exactly hopeful.

**Comment by keithzg** [comment]
Well, there's at least a few factors here that spring to my mind:
1. Including the source code alongside the object code is nonetheless still an option for satisfying the license, so may well be followed when practical (I can imagine situations in which it would be the easier option).
2. Only one person would need to download the source code in any given physical area, and then they'd be able to pass on the source code via a tangible medium (or short-range, unmetered networking) to others.
3. Requiring the source code to be included with the products is itself not always practical, for one reason or another, and thus would be a large additional requirement for this license to have.

**Comment by richardfontana** [comment]
@11Kilobytes 's concern is legitimate (and related to the reasons why the approach in copyleft-next is not taken in the GNU GPL) but I believe the benefit of simplification of compliance in what I think would be the typical case outweighs that concern.
