### ISSUE TITLE
Restrictions on usage as training data

### ISSUE THREAD

**Issue by Seirdy** [copyleft-next/copyleft-next#54]
Proposal: add a clause stating that any software that uses copyleft-next-licensed software as training data needs to also be licensed under a copyleft license.

This could also be part of a sibling license as proposed in [Issue 51](https://github.com/copyleft-next/copyleft-next/issues/51).

Rationale: Software such as GitHub Copilot can regurgitate AGPL-licensed software snippets used as training data. Someone could theoretically train a model with a piece of AGPL-software given disproportionate weight to regurgitate AGPL-licensed software. On top of this, the tool that enabled this itself could be proprietary, making it easier to hide its workings and claim that the resulting code is a transformative work.

Requiring the trainable software to be copyleft could help expose these inner workings and allow others to understand whether or not the generated text is indeed a transformative work, or if it's just a license violation with extra steps.

**Comment by owlshrimp** [comment]
I think asking that the program processing the source code be made copyleft is unwarranted. We don't force people to edit a program with a copyleft-licenced text editor or otherwise compel processing of the source code with only copyleft-licenced tools in any other context.

**Comment by owlshrimp** [comment]
I think a lot of caution is warranted in trying to close this loophole that programs like Copilot potentially introduce.

> Someone could theoretically train a model with a piece of AGPL-software given disproportionate weight to regurgitate AGPL-licensed software. On top of this, the tool that enabled this itself could be proprietary, making it easier to hide its workings and claim that the resulting code is a transformative work.

*Theoretically*

The trained model itself might encode whole works, or perhaps only extracted ideas and concepts. I'm not sure anyone has any tools (or even conceptual frameworks) to know one from the other. Additionally, a "contaminated" model may still successfully reproduce (in a new form) only non-copyrightable concepts and ideas, even for some time before slipping up, making verification challenging.

I don't think it can be definitively said if a given model is committing infringement given the above (except with obvious cases), and determination of derivative works is already a thorny issue. For obvious letter-identical reproduction, is this not covered by regular copyright regardless of method?

I think a hardline approach to disallow all ML processing is also likely to conflict with legitimate use cases. Many useful IDE tools may make self-contained use of ML but also be used while editing covered code, for example. The definition of "machine learning" is also a moving target [1] so developing a nuanced definition that doesn't ensnare benign processing of code (eg. reporting flaws, even in copyrighted report documents) seems difficult.

I think there should definitely be discussion of potential code laundering, but writing licence language around it seems premature.

[1] Neural networks are currently popular. Before them many, many different forms of "machine learning" (eg. support vector machines, genetic algorithms, perceptrons, nearest-neighbor, Viola-Jones, etc) have existed for several decades. More continually appear.

IANAL, Etc.

P.S. For additional interesting reading, I believe LWN has an article a few years ago debating whether machine leaning models (tables of numbers) could ever be considered open source without shipping the entire training set and expecting users to do costly retraining.

**Comment by Seirdy** [comment]
On Sun, Jul 18, 2021 at 09:19:59PM -0700, Matt wrote:
>I think there should definitely be discussion of potential code 
>laundering, but writing licence language around it seems premature.

Agreed; this wasn't really an actual proposal as much as an idea that we 
should start thinking about. There needs to be some mechanism to prevent 
obfuscating the workings of models that produce allegedly-derived works, 
but going through the legalese of how to best implement this will be a 
challenge.

>P.S. For additional interesting reading, I believe LWN has an article a 
>few years ago debating whether machine leaning models (tables of 
>numbers) could ever be considered open source without shipping the 
>entire training set and expecting users to do costly retraining.

Yeah; on that note, we should see if there's a way to require vendors to 
share training data and/or parameters; the rationale is similar to 
requiring software served over a network to distribute backend code via 
the AGPL.

Some way to mitigate the lock-in effects of bespoke hardware (like 
Google's TPUs) should also exist, though that sounds a bit out of scope 
for a software license.

-- 
/Seirdy

**Comment by richardfontana** [comment]
> Proposal: add a clause stating that any software that uses copyleft-next-licensed software as training data needs to also be licensed under a copyleft license. 

Thanks for the proposal but this would make copyleft-next violate current norms around FOSS licensing. copyleft-next is intended to be a FOSS license as that is _currently_ understood. Since this is beyond the scope of (or in conflict with) the goals of the project, I'll close this issue.

**Comment by richardfontana** [comment]
> I don't think it can be definitively said if a given model is committing infringement given the above (except with obvious cases), and determination of derivative works is already a thorny issue. For obvious letter-identical reproduction, is this not covered by regular copyright regardless of method?

Yes, I would assume so.

> I think there should definitely be discussion of potential code laundering, but writing licence language around it seems premature.

Agreed.

**Comment by owlshrimp** [comment]
> Yeah; on that note, we should see if there's a way to require vendors to share training data and/or parameters; the rationale is similar to requiring software served over a network to distribute backend code via the AGPL. Some way to mitigate the lock-in effects of bespoke hardware (like Google's TPUs) should also exist, though that sounds a bit out of scope for a software license.

The issue isn't so much that they don't share the training data or parameters. If the AGPL is sufficient for online services [1] you could probably make some kind of argument that the parameters are important to the running of the online service. Not exactly part of it (I don't know how a GPL'd spreadsheet of weights would work) but perhaps similar to the provisions in the GPLv3 that try to fend off Tivoization.

The bigger issue LWN's article grappled with is that the parameters are essentially a binary blob for which there is never corresponding source code. The only way to reproduce a model is basically to retrain it from scratch which requires huge time/effort. Unshared datasets are perhaps an issue, but many are scraped from public data or are public themselves.

There isn't really a problem of lock-in with TPUs. They're powerful, yes, but the math is well understood and many different hardware accelerators exist. These include both nvidia and now AMD GPUs [2] in the case of pytorch models, or custom accelerators one could build on an FPGA. GPUs are currently by far the most popular method. More options are added every month and the real problem here is that powerful computers aren't free as in beer. Dunno how to solve that one other than by waiting.

[1] though some argue the AGPL is either useless or a non-free EULA (as written), see https://twitter.com/marcan42/status/1377899950164516867

[2] Yay open-source ROCm!

**Comment by owlshrimp** [comment]
There's a pretty good argument here, regarding the interpretation at the root of this thread: https://mjg59.dreamwidth.org/57615.html

Summary:

Essentially, if you accept the argument that the output of a model is a derived work of the training or input data, then any proprietary code trained on remains proprietary code in the output. Under Github's interpretation, the output is *not* a derived work, not proprietary, and people are free to take the output of the model and go on with their day. Concepts from a under a variety of open source licences may be incorporated into proprietary code, but at the same and only under Github's view, proprietary code's concepts can be incorporated into open source.

This is directly against the wishes of the copyright maximalists who would prefer that:

1. Nobody ever get to see their proprietary code.
2. Anyone who does see it or tinkers with the result be considered "tainted" and prevented from ever working on an open source replacement.

The GPL was created *only* as a tool to weaken the stance of these maximalists who wish to keep code to themselves and out of the public sphere. Also argued is that views which enhance copyright's reach benefit companies wishing to keep code proprietary (who have lots of lawyers) far more than it benefits people using the GPL.

As for who's getting more from who, it's noted is that proprietary code on Github FAR outnumbers code under any open source licence and presumable was used during training.

I suppose that it could be a sizable liability problem is Github's view is found wrong in court, but have to admit that they have produced a pretty good laundering device if one wanted to cover one's tracks.

**Comment by Seirdy** [comment]
On Tue, Jul 20, 2021 at 02:18:21PM -0700, Matt wrote:
> Though some argue the AGPL is either useless or a non-free EULA (as written), see https://twitter.com/marcan42/status/1377899950164516867

The latter criticism seems to miss the point of both copyleft licenses 
and of EULAs.

The purpose of an EULA is to restrict a user's freedom while the purpose 
of the GNU AGPLv3 is to allow more freedom than what the GPLv3 provides 
by closing a loophole to restrict freedom on others. Debates on whether 
an individual's freedom to restrict freedom of others enables more or 
less freedom in a population are typically remniscient of conversations 
about the "paradox of intolerance" (does tolerating intolerance further 
tolerance) and the social contract theory (can restricting certain 
rights protect other rights). I'm personally of the opinion that 
tolerating intolerance does not create a more tolerant society, 
restriction of certain rights can safeguard other rights for a net gain, 
and allowing others to exercise the freedom to take freedom away does 
not result in a more free society.

The purpose of a more permissive license is to enable nonfree derivative 
works; the purpose of the GNU AGPLv3 is to only allow free derivatives.  
Strict copyleft licenses maximize freedom by prohibiting further 
restriction of it; it's a local maxima of "user freedom" as a function 
of "vendor privileges" when looking at systems at a larger scale.

-- 
/Seirdy
